# trigger all activity on main branch 
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
# linting all codebase in project 
- stage: lint
  displayName: Lint with EsLint
  jobs:
  - job: lint
    displayName: lint all codebase
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
        checkLatest: true
    - script: |
        npm install --only=dev
        npm run lint

# doing all tests in project
- stage: test
  displayName: Test with Jest
  dependsOn: []
  jobs:
  - job: test
    displayName: test all codebase
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
        checkLatest: true
    - script: |
        npm install --only=dev
        npm run test

# build all source code when checked
- stage: build
  displayName: Build whole codebase
  dependsOn: [ test, lint ]
  jobs:
    - job: builder
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '14.x'
            checkLatest: true
        - script: |
            echo " Build whole codebase for production: "
            npm install --only=prod
            npm run build
