# trigger all activity on main branch 
trigger:
- main

stages:
# linting all codebase in project 
- stage: lint
  displayName: Lint with EsLint
  jobs:
  - job: lint
    pool: ubuntu-latest
    displayName: lint all codebase
    steps:
    - script: |
        npm install --only=dev
        npm run lint

# doing all tests in project
- stage: test
  displayName: Test with Jest
  dependsOn: []
  jobs:
  - job: test
    pool: ubuntu-latest
    displayName: test all codebase
    steps:
    - script: |
        npm install --only=dev
        npm run test

# build all source code when checked
- stage: build
  displayName: Build whole codebase
  dependsOn: [ test, lint ]
  jobs:
    - job: builder
      pool: ubuntu-latest
      steps:
        - script: |
            echo " Build whole codebase for production: "
            npm install
            npm run build
            